fading_square_opts = {}
fading_square_opts['dataset'] = 'fading_squares'
fading_square_opts['experiment_path'] = 'fading_squares/exp1'
fading_square_opts['z_dim'] = 2
fading_square_opts['print_log_information'] = True
fading_square_opts['make_pictures_every'] = 500
fading_square_opts['save_every'] = 500
fading_square_opts['plot_axis_walks'] = True
fading_square_opts['axis_walk_range'] = 1
fading_square_opts['plot_losses'] =  True
fading_square_opts['print_log_information'] = True
fading_square_opts['batch_size'] = 100
fading_square_opts["encoder_architecture"] = 'FC_dsprites'
fading_square_opts["decoder_architecture"] = 'FC_dsprites'
fading_square_opts['z_mean_activation'] = None
fading_square_opts['encoder_distribution'] = 'uniform'
fading_square_opts['logvar-clipping'] = [-20,5]
fading_square_opts['z_prior'] = 'uniform'
fading_square_opts['loss_reconstruction'] = 'bernoulli'
fading_square_opts['loss_regulariser'] = 'WAE_MMD'
fading_square_opts['lambda_imq'] = 20.0
fading_square_opts['IMQ_length_params'] = [0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10.0]
fading_square_opts['z_logvar_regularisation'] = None
#fading_square_opts['lambda_logvar_regularisation'] = 0.5
fading_square_opts['optimizer'] = 'adam'
fading_square_opts['learning_rate_schedule'] = [(1e-4, 10000), (1e-5, 20000)]


dsprites_opts = {}
dsprites_opts['dataset'] = 'dsprites'
dsprites_opts['experiment_path'] = 'dsprites/exp1'
dsprites_opts['z_dim'] = 16
dsprites_opts['print_log_information'] = True
dsprites_opts['make_pictures_every'] = 500
dsprites_opts['save_every'] = 500
dsprites_opts['plot_axis_walks'] = False
#dsprites_opts['axis_walk_range'] = 1
dsprites_opts['plot_losses'] =  False
dsprites_opts['print_log_information'] = True
dsprites_opts['batch_size'] = 100
dsprites_opts["encoder_architecture"] = 'FC_dsprites'
dsprites_opts["decoder_architecture"] = 'FC_dsprites'
dsprites_opts['z_mean_activation'] = 'tanh'
dsprites_opts['encoder_distribution'] = 'gaussian'
dsprites_opts['logvar-clipping'] = [-20,5]
dsprites_opts['z_prior'] = 'gaussian'
dsprites_opts['loss_reconstruction'] = 'bernoulli'
dsprites_opts['loss_regulariser'] = 'WAE_MMD'
dsprites_opts['lambda_imq'] = 20.0
dsprites_opts['IMQ_length_params'] = [0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10.0]
dsprites_opts['z_logvar_regularisation'] = "L1"
dsprites_opts['lambda_logvar_regularisation'] = 3.0
dsprites_opts['optimizer'] = 'adam'
dsprites_opts['learning_rate_schedule'] = [(1e-4, 10000), (1e-5, 20000)]


opts = dsprites_opts
